// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using beslenme.Context;

#nullable disable

namespace beslenme.Migrations
{
    [DbContext(typeof(uContext))]
    [Migration("20240524130042_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("beslenme.Entitites.Hesap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("HesapTuru")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sonuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Hesap");
                });

            modelBuilder.Entity("beslenme.Entitites.Kullanici", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("kullaniciAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sifre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Kullanici");
                });

            modelBuilder.Entity("beslenme.Entitites.Paketler", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("PaketAciklama")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaketAd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PaketFiyat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("Paketlers");
                });

            modelBuilder.Entity("beslenme.Entitites.Sepet", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("adet")
                        .HasColumnType("int");

                    b.Property<decimal?>("fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("indirimKod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("indirimTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("kullaniciAd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("toplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("Sepet");
                });

            modelBuilder.Entity("beslenme.Entitites.Urun", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("aciklama")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("adet")
                        .HasColumnType("int");

                    b.Property<decimal?>("fiyat")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.ToTable("Urun");
                });

            modelBuilder.Entity("beslenme.Entitites.UserProp", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal?>("boy")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("cinsiyet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("gunlukAdimSayisi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("kilo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("userId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("yas")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("UserProp");
                });
#pragma warning restore 612, 618
        }
    }
}
